[package]
name = "teleport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = { version = "1.4.1", features = ["digest", "traits-preview"] }
ethers = "2.0.8"
libp2p = { version = "0.52.0", features = [
    "gossipsub",
    "macros",
    "tcp",
    "async-std",
    "tokio",
    "noise",
    "ed25519",
    "identify",
] }
prost = "0.11.9"
serde = "1.0.183"
sled = "0.34.7"
thiserror = "1.0.44"
tonic = "0.9.2"
tokio = { version = "1.31.0", features = ["full"] }
libp2p-mplex = "0.40.0"

[build-dependencies]
prost-build = "0.11.9"
tonic-build = "0.9.2"
